apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:11.0-base
    resources:
      limits:
        nvidia.com/gpu: 1  # Requesting 1 GPU
    command: ["nvidia-smi"]  
  nodeSelector:
    cloud.google.com/gke-accelerator: "nvidia-tesla-t4"  # Specifying GPU type explicitly
