site_name: BensBot Trading System
site_description: Documentation for the BensBot trading system
site_author: Ben Dickinson
repo_url: https://github.com/TheClitCommander/BensBot

theme:
  name: material
  palette:
    # Match the trading dashboard's dark blue professional design
    primary: indigo
    accent: indigo
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [trading_bot]
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Configuration:
    - Overview: configuration.md
    - Environment Variables: environment-variables.md
    - API Keys: api-keys.md
  - Core Components:
    - Typed Settings: typed-settings.md
    - Risk Management: risk-management.md
    - Strategy System: strategy-system.md
    - Orchestrator: orchestrator.md
    - Backtesting: backtesting.md
  - APIs and Integration:
    - API Overview: api-overview.md
    - Market Intelligence API: market-intelligence-api.md
    - Authentication: authentication.md
    - News Integration: news-integration.md
  - Development:
    - Setup: development-setup.md
    - Testing: testing.md
    - Contribution Guidelines: contributing.md
