# EvoTrader Debug Configuration

simulation:
  seed: 42
  bots: 10  # Reduced number for debugging
  duration_days: 60
  initial_balance: 10000.0
  data_provider: sequential
  symbols: ["BTC/USD", "ETH/USD", "XRP/USD", "LTC/USD"]

logging:
  level: DEBUG  # Increased verbosity
  file: logs/evotrader_debug.log

# Enhanced evolution settings
evolution:
  population_size: 10
  selection_method: tournament
  tournament_size: 3
  mutation_rate: 0.1
  elite_percent: 0.2
  # Strategy crossover settings
  enable_crossover: true
  crossover_rate: 0.3
  crossover_percent: 0.3

# Advanced fitness settings
fitness:
  balance_weight: 0.4
  sharpe_weight: 0.3
  drawdown_weight: 0.2
  consistency_weight: 0.1
  severe_drawdown: 0.4
  medium_drawdown: 0.25

strategy:
  default:
    type: trend_following
    parameters:
      lookback: 14
      threshold: 0.01
      debug_mode: true  # Enable debug mode for all strategies

# Data provider settings - extended history
data_provider:
  lookback_window: 300  # Increased lookback window
  calculate_indicators: true

output:
  directory: debug_results
