# Default EvoTrader Configuration

simulation:
  seed: 42
  bots: 100
  duration_days: 60  # Increased simulation duration to provide more trading opportunities
  initial_balance: 10000.0  # More realistic starting capital
  data_provider: sequential  # Options: random_walk, sequential
  symbols: ["BTC/USD", "ETH/USD", "XRP/USD", "LTC/USD"]

logging:
  level: INFO
  file: logs/evotrader.log

# Enhanced evolution settings
evolution:
  population_size: 100
  selection_method: tournament  # tournament or fitness_proportional
  tournament_size: 5
  mutation_rate: 0.1
  elite_percent: 0.1
  # Strategy crossover settings
  enable_crossover: true
  crossover_rate: 0.3
  crossover_percent: 0.3  # Percentage of population created via crossover

# Advanced fitness settings
fitness:
  balance_weight: 0.4       # Weight for final balance in fitness calculation
  sharpe_weight: 0.3        # Weight for risk-adjusted returns
  drawdown_weight: 0.2      # Weight for drawdown penalty
  consistency_weight: 0.1   # Weight for trading consistency
  severe_drawdown: 0.4      # Threshold for severe drawdown penalty (40%)
  medium_drawdown: 0.25     # Threshold for medium drawdown penalty (25%)

strategy:
  default:
    type: trend_following
    parameters:
      lookback: 14
      threshold: 0.01

output:
  directory: results

# Sequential data provider settings
data_provider:
  lookback_window: 200      # Increased lookback window for better indicator calculations
  calculate_indicators: true # Pre-calculate common indicators
