version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes: [ "./backend:/app/backend", "./.env:/app/.env", "./bensbot.db:/app/bensbot.db" ]
    command: bash -lc "pip install fastapi uvicorn[standard] httpx tenacity pyjwt && uvicorn backend.app:app --host 0.0.0.0 --port 8787"
    ports: [ "8787:8787" ]
    restart: unless-stopped
    env_file: .env
  ui:
    image: python:3.11-slim
    working_dir: /app
    volumes: [ "./dashboard:/app/dashboard", "./.env:/app/.env" ]
    command: bash -lc "pip install streamlit requests && streamlit run dashboard/app.py --server.port 8788 --server.address 0.0.0.0"
    ports: [ "8788:8788" ]
    restart: unless-stopped
    env_file: .env
