# Trading Bot Pipeline Configuration

# Output directory for models, results and logs
output_dir: "./output"

# Data configuration
data:
  market_data_path: "./data/market_data.csv"
  sentiment_data_path: "./data/sentiment_data.csv"
  # Split data for training and testing
  train_start_date: "2018-01-01"
  train_end_date: "2022-12-31"
  test_start_date: "2023-01-01"
  test_end_date: "2023-12-31"

# Feature engineering configuration
feature_engineering:
  # Technical indicator settings
  include_technicals: true
  lookback_periods: [5, 10, 20, 50]
  ta_feature_sets: ["momentum", "trend", "volatility", "volume"]
  
  # Additional features
  include_time_features: true
  include_price_patterns: true
  include_lags: true
  lags: [1, 3, 5, 10]
  
  # Market regime detection
  detect_market_regime: true
  high_vol_threshold: 0.015
  trend_threshold: 25
  mean_rev_threshold: 0.4
  
  # Feature transformation
  normalize_features: true
  scaling_method: "standard"  # "standard" or "minmax"
  feature_selection: "importance"
  max_features: 50

# Target configuration
target:
  # Return horizons to generate labels for
  horizons: [1, 5, 10, 20]
  # Return thresholds for classification
  thresholds: [0.0, 0.005, 0.01, 0.02]
  # Primary target to use for model training
  primary_horizon: 5
  primary_threshold: 0.01

# Model configuration
model:
  # Model type (classification or regression)
  type: "classification"
  # Algorithm
  model_algorithm: "xgboost"  # logistic_regression, random_forest, xgboost, lightgbm
  # Model hyperparameters
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_seed: 42
  # Class weight (for classification)
  class_weight: "balanced"
  
  # Meta-model for ensemble
  meta_algorithm: "random_forest"
  meta_n_estimators: 50
  meta_max_depth: 3
  meta_learning_rate: 0.05

# Evaluation configuration
evaluation:
  # Transaction costs and slippage
  transaction_cost: 0.001  # 0.1% per trade
  slippage_rate: 0.0005    # 0.05% slippage
  
  # Walk-forward parameters
  train_size: 0.6
  test_size: 0.2
  step_size: 0.1
  
  # Position sizing
  position_size: 1.0
  allow_short: true
  confidence_threshold: 0.55
  
  # Performance calculation
  trading_periods_per_year: 252  # For annualizing Sharpe ratio

# Deployment configuration
deployment:
  # API settings
  api_host: "0.0.0.0"
  api_port: 8000
  
  # Model selection
  use_latest_model: true
  model_refresh_interval: 3600  # In seconds

broker:
  api_key: YOUR_TRADIER_API_KEY
  account_id: YOUR_ACCOUNT_ID

# Optional settings
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

database:
  url: "mongodb://localhost:27017"
  name: "trading_bot"

redis:
  url: "redis://localhost:6379" 