apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot-trading-system
spec:
  template:
    spec:
      containers:
      - name: trading-system
        image: ghcr.io/your-org/trading-bot-trading_system:develop
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: TRADING_ENABLED
          value: "false"  # Disabled in dev
        - name: USE_PAPER_TRADING
          value: "true"   # Always use paper trading in dev 