# Trading API Configuration
# Paper Trading Accounts

tradier:
  account_number: VA1201776
  api_key: KU2iUnOZIUFre0wypgyOn8TgmGxI
  
alpaca:
  endpoint: https://paper-api.alpaca.markets/v2
  api_key: PKYBHCCT1DIMGZX6P64A
  api_secret: ssidJ2cJU0EGBOhdHrXJd7HegoaPaAMQqs0AU2PO
